<a href="https://colab.research.google.com/github/HoangThai2k5/THDeepLearning/blob/main/Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY


In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(a)
print(a.shape)
print(a.dtype)

[1 2 3 4 5]
(5,)
int64


In [3]:
b = np.array([
    [1., 2., 3.],
    [4., 5., 6.]
])

print(b)
print(b.shape)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)


In [4]:
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12]]
])

print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [5]:
x = np.zeros((2, 3))
print(x)

y = np.ones((2, 3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:

e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)

f = e.reshape(3, 2)
print(f)


g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])

print(g)
print(g.shape)

# Các phép biến đổi hình dạng (reshape) trên mảng g
h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [8]:


# Trải phẳng mảng 2 chiều
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)

# Trải phẳng mảng 3 chiều
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])
j = g.flatten()
print(j)


[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [9]:

f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

# Xếp chồng theo chiều ngang (Horizontal Stack)
h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)


# Xếp chồng theo chiều dọc (Vertical Stack)
v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)


Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [10]:


a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)

b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)

c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [82  5 50 19 15]
Random 2-D array
 [[66 33 88 24]
 [48 58 94 77]
 [39 41  9 25]]
Random 3-D array
 [[[16 91 54]
  [88 90 14]
  [78 45 50]
  [61 71 23]]

 [[81 20 48]
  [56 43 90]
  [35 73 91]
  [26 96  0]]

 [[12 53 71]
  [29 23 51]
  [ 2  3 87]
  [93 49 75]]]


In [11]:


# sinh ngẫu nhiên mảng số thực [0, 1]
a = np.random.rand(5)
print('Random 1-D array\n', a)


b = np.random.rand(3, 4)
print('Random 2-D array\n', b)


c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.38076588 0.66198278 0.20972789 0.42261168 0.49359286]
Random 2-D array
 [[0.49296427 0.4018535  0.44763128 0.07484423]
 [0.64999837 0.18295004 0.82812382 0.69397537]
 [0.48678337 0.10760887 0.47531403 0.98491188]]
Random 3-D array
 [[[0.91730007 0.43750204 0.22129765]
  [0.25942421 0.75236971 0.40027406]
  [0.71363977 0.43472071 0.23997444]
  [0.70147121 0.06561056 0.84301454]]

 [[0.89517356 0.29112833 0.22197295]
  [0.01824217 0.21323451 0.349254  ]
  [0.87416785 0.24621164 0.41049596]
  [0.24847482 0.42529647 0.80226415]]

 [[0.44553382 0.56881436 0.58236826]
  [0.24915089 0.92847856 0.79019599]
  [0.46650756 0.94720472 0.74626692]
  [0.02328032 0.10907789 0.40880294]]]


In [12]:
a = np.random.normal(5,0.5,10)
print(a)

[5.11801905 5.5935371  5.75272747 4.94778576 5.93715615 4.57789281
 5.04256271 4.85049776 5.95041796 4.25783635]


In [13]:


# sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)

# sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

12
[[14 16  8 16 10]
 [ 4 18 14 16  6]
 [ 8 14  4 12  2]]


In [14]:

# Tạo ma trận 5 x 5 toàn số 1
A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)

# Thử thay đổi hàng thứ 3 bằng np.array()
np.array(A)[2] = 2
print('Change values of third row with array\n', A)

# Thử thay đổi hàng thứ 3 bằng np.asarray()
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:

# Tạo dãy số nguyên từ 1 đến (20-1)
a = np.arange(1, 20)
print(a)


# Tạo dãy số nguyên từ 1 đến (20-1), mỗi bước tăng 2 giá trị
b = np.arange(1, 20, 2)
print(b)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [16]:


a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)

# --- Slice theo hàng ---
print('first row:', a[0])   # Lấy hàng đầu tiên (chỉ số 0)
print('second row:', a[1])  # Lấy hàng thứ hai (chỉ số 1)

# --- Indexing & Slicing kết hợp ---
# Cấu trúc: a[hàng, cột]
# Dấu : đại diện cho "tất cả"

print('Second column:', a[:, 1])  # Lấy tất cả hàng, nhưng chỉ lấy cột thứ 2 (chỉ số 1)
print('first column:', a[:, 0])   # Lấy tất cả hàng, nhưng chỉ lấy cột đầu tiên (chỉ số 0)

# Lấy 2 giá trị đầu tiên của hàng thứ 2
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column: [1 4]
First two values of second row: [4 5]


In [18]:
a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [20]:
# Quy tắc: [số dòng, số cột]
a = np.array([(1, 2, 3), (4, 5, 6)])
print('first row:', a[0])
print('second row:', a[1])
print('Second column:', a[:, 1]) # Lấy tất cả dòng của cột chỉ số 1
print('first column:', a[:, 0])  # Lấy tất cả dòng của cột chỉ số 0
print('First two values of second row:', a[1, :2])

first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column: [1 4]
First two values of second row: [4 5]


# Pandas



In [26]:
import pandas as pd
# Tạo series từ list
a = pd.Series([1., 2., 3.])
print(a)

# Tạo series với index tùy chỉnh
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b['a'])

# Tạo series từ dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
1.0
day1    420
day2    380
day3    390
dtype: int64


In [28]:
# Chuyển từ Numpy sang Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)

# Chuyển từ Pandas ngược lại Numpy
numpy_h = np.array(df_h)

# Tạo DataFrame từ dictionary có tên cột
dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)

# Tạo DataFrame từ mảng ngẫu nhiên 20x4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head()) # In 5 dòng đầu tiên

        so1       so2       so3       so4
0  0.541690 -0.089741  0.822111  2.052647
1  0.000014 -0.115702 -0.526659  0.524759
2  0.374169 -1.987382  0.479266 -0.074485
3  0.078584  3.340466  0.307026 -0.560742
4 -1.201247  0.351499  1.407824  0.759587


In [32]:


# Khởi tạo DataFrame thứ nhất
df1 = pd.DataFrame({
    'Name': ['John', 'Smith', 'Paul'],
    'Age': [25, 30, 50]
}, index=[0, 1, 2])

# Khởi tạo DataFrame thứ hai
df2 = pd.DataFrame({
    'Name': ['Adam', 'Smith'],
    'Age': [26, 11]
}, index=[3, 4])

# Nối hai DataFrame lại với nhau
df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)

# Xóa những giá trị ở cột Name trùng nhau (Giữ lại giá trị đầu tiên xuất hiện)
print('Drop duplicate values in DataFrame\n', df_concat.drop_duplicates('Name'))

# Sắp xếp DataFrame theo giá trị của cột 'Age' (mặc định là tăng dần)
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))

# Đổi tên cột trong DataFrame
df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicate values in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


In [ ]:


# Đường dẫn đến tệp tin CSV
path = '/content/sample_data/Salary_Data.csv'

# Định nghĩa tên cột cho DataFrame
COLUMNS = ['YearsExperience', 'Salary']

# Cách 1: Đọc CSV và tự định nghĩa tên cột [cite: 433, 434]
df_csv = pd.read_csv(path, skipinitialspace=True, names=COLUMNS, index_col=False)
print(df_csv.head()) # Hiển thị 5 dòng đầu tiên [cite: 414]
print(df_csv.shape)  # Kiểm tra kích thước mảng (số dòng, số cột) [cite: 26]

# Cách 2: Đọc CSV sử dụng tiêu đề (header) có sẵn trong tệp tin
df_csv1 = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv1.head())
print(df_csv1.shape)

In [ ]:


# Đường dẫn đến tệp dữ liệu Fish.csv
path = '/content/sample_data/Fish.csv'

# Đọc dữ liệu từ CSV
df_csv = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv.head())

# 1. Gom nhóm theo 'Species' và tính giá trị trung bình (mean) cho tất cả các cột số
print(df_csv.groupby(['Species']).mean().head())

# 2. Gom nhóm theo 'Species', nhưng chỉ lấy cột 'Weight' và tìm giá trị nhỏ nhất (min)
print(df_csv.groupby(['Species'])['Weight'].min().head())

# 3. Gom nhóm kết hợp theo nhiều cột ('Species' và 'Height'), sau đó tìm Weight nhỏ nhất
print(df_csv.groupby(['Species', 'Height'])['Weight'].min().head())