<a href="https://colab.research.google.com/github/HoangThai2k5/THDeepLearning/blob/main/Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY


In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(a)
print(a.shape)
print(a.dtype)

[1 2 3 4 5]
(5,)
int64


In [3]:
b = np.array([
    [1., 2., 3.],
    [4., 5., 6.]
])

print(b)
print(b.shape)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)


In [4]:
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12]]
])

print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [5]:
x = np.zeros((2, 3))
print(x)

y = np.ones((2, 3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:

e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)

f = e.reshape(3, 2)
print(f)


g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])

print(g)
print(g.shape)

# Các phép biến đổi hình dạng (reshape) trên mảng g
h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [8]:


# Trải phẳng mảng 2 chiều
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)

# Trải phẳng mảng 3 chiều
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])
j = g.flatten()
print(j)


[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [9]:

f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

# Xếp chồng theo chiều ngang (Horizontal Stack)
h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)


# Xếp chồng theo chiều dọc (Vertical Stack)
v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)


Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [10]:


a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)

b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)

c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [82  5 50 19 15]
Random 2-D array
 [[66 33 88 24]
 [48 58 94 77]
 [39 41  9 25]]
Random 3-D array
 [[[16 91 54]
  [88 90 14]
  [78 45 50]
  [61 71 23]]

 [[81 20 48]
  [56 43 90]
  [35 73 91]
  [26 96  0]]

 [[12 53 71]
  [29 23 51]
  [ 2  3 87]
  [93 49 75]]]


In [11]:


# sinh ngẫu nhiên mảng số thực [0, 1]
a = np.random.rand(5)
print('Random 1-D array\n', a)


b = np.random.rand(3, 4)
print('Random 2-D array\n', b)


c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.38076588 0.66198278 0.20972789 0.42261168 0.49359286]
Random 2-D array
 [[0.49296427 0.4018535  0.44763128 0.07484423]
 [0.64999837 0.18295004 0.82812382 0.69397537]
 [0.48678337 0.10760887 0.47531403 0.98491188]]
Random 3-D array
 [[[0.91730007 0.43750204 0.22129765]
  [0.25942421 0.75236971 0.40027406]
  [0.71363977 0.43472071 0.23997444]
  [0.70147121 0.06561056 0.84301454]]

 [[0.89517356 0.29112833 0.22197295]
  [0.01824217 0.21323451 0.349254  ]
  [0.87416785 0.24621164 0.41049596]
  [0.24847482 0.42529647 0.80226415]]

 [[0.44553382 0.56881436 0.58236826]
  [0.24915089 0.92847856 0.79019599]
  [0.46650756 0.94720472 0.74626692]
  [0.02328032 0.10907789 0.40880294]]]
