<a href="https://colab.research.google.com/github/HoangThai2k5/THDeepLearning/blob/main/Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY


In [59]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(a)
print(a.shape)
print(a.dtype)

[1 2 3 4 5]
(5,)
int64


In [60]:
b = np.array([
    [1., 2., 3.],
    [4., 5., 6.]
])

print(b)
print(b.shape)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)


In [61]:
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12]]
])

print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [62]:
x = np.zeros((2, 3))
print(x)

y = np.ones((2, 3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [63]:

e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)

f = e.reshape(3, 2)
print(f)


g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])

print(g)
print(g.shape)

# Các phép biến đổi hình dạng (reshape) trên mảng g
h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [64]:


# Trải phẳng mảng 2 chiều
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)

# Trải phẳng mảng 3 chiều
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])
j = g.flatten()
print(j)


[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [65]:

f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

# Xếp chồng theo chiều ngang (Horizontal Stack)
h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)


# Xếp chồng theo chiều dọc (Vertical Stack)
v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)


Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [66]:


a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)

b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)

c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [46 65 16  1 23]
Random 2-D array
 [[10 83 31  0]
 [ 1 67 64 24]
 [32 86 16 81]]
Random 3-D array
 [[[58 45 61]
  [14  4 41]
  [89 24 64]
  [14 83 15]]

 [[82 12 21]
  [90 23 47]
  [52 31 84]
  [40  8 72]]

 [[21 76 76]
  [28 34  5]
  [88 31 66]
  [86  8 39]]]


In [67]:


# sinh ngẫu nhiên mảng số thực [0, 1]
a = np.random.rand(5)
print('Random 1-D array\n', a)


b = np.random.rand(3, 4)
print('Random 2-D array\n', b)


c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.56542221 0.96267652 0.12741478 0.50169008 0.35190064]
Random 2-D array
 [[0.21481992 0.92626983 0.90623437 0.37075594]
 [0.78383128 0.17344649 0.47897384 0.59167493]
 [0.96702815 0.34894946 0.41522031 0.12576277]]
Random 3-D array
 [[[0.2484568  0.59667669 0.61342433]
  [0.89458554 0.59639009 0.42416671]
  [0.97350977 0.33947063 0.71963839]
  [0.25214326 0.64422214 0.35613098]]

 [[0.36107807 0.72237081 0.79842564]
  [0.86285896 0.56022178 0.69681457]
  [0.33524952 0.46662959 0.83361297]
  [0.74556689 0.05017519 0.07658839]]

 [[0.34377661 0.0833688  0.16029734]
  [0.46702656 0.71343307 0.54717692]
  [0.40172568 0.40154046 0.51900458]
  [0.6574568  0.12206422 0.21302035]]]


In [68]:
a = np.random.normal(5,0.5,10)
print(a)

[5.44300439 5.537081   4.25329837 4.74725286 5.64342496 5.24967268
 4.98906394 5.38202711 5.84630972 5.86827989]


In [69]:


# sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)

# sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

18
[[ 2  4  4  6  4]
 [ 6 14 12  2  4]
 [ 6  8 18  6 10]]


In [70]:

# Tạo ma trận 5 x 5 toàn số 1
A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)

# Thử thay đổi hàng thứ 3 bằng np.array()
np.array(A)[2] = 2
print('Change values of third row with array\n', A)

# Thử thay đổi hàng thứ 3 bằng np.asarray()
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [71]:

# Tạo dãy số nguyên từ 1 đến (20-1)
a = np.arange(1, 20)
print(a)


# Tạo dãy số nguyên từ 1 đến (20-1), mỗi bước tăng 2 giá trị
b = np.arange(1, 20, 2)
print(b)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [72]:


a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)

# --- Slice theo hàng ---
print('first row:', a[0])   # Lấy hàng đầu tiên (chỉ số 0)
print('second row:', a[1])  # Lấy hàng thứ hai (chỉ số 1)

# --- Indexing & Slicing kết hợp ---
# Cấu trúc: a[hàng, cột]
# Dấu : đại diện cho "tất cả"

print('Second column:', a[:, 1])  # Lấy tất cả hàng, nhưng chỉ lấy cột thứ 2 (chỉ số 1)
print('first column:', a[:, 0])   # Lấy tất cả hàng, nhưng chỉ lấy cột đầu tiên (chỉ số 0)

# Lấy 2 giá trị đầu tiên của hàng thứ 2
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column: [1 4]
First two values of second row: [4 5]


In [73]:
a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [74]:
# Quy tắc: [số dòng, số cột]
a = np.array([(1, 2, 3), (4, 5, 6)])
print('first row:', a[0])
print('second row:', a[1])
print('Second column:', a[:, 1]) # Lấy tất cả dòng của cột chỉ số 1
print('first column:', a[:, 0])  # Lấy tất cả dòng của cột chỉ số 0
print('First two values of second row:', a[1, :2])

first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column: [1 4]
First two values of second row: [4 5]


NUMPY: Xử lý mảng đa chiều  
Khởi tạo: Bạn đã tạo các mảng (Array) từ 1-chiều đến 3-chiều, cũng như các ma trận đặc biệt như ma trận toàn số 0 (zeros), số 1 (ones) hoặc ma trận đơn vị (identity).  
Biến đổi hình dạng: Sử dụng reshape để thay đổi kích thước ma trận và flatten để trải phẳng mảng nhiều chiều về 1-chiều.  
Thao tác dữ liệu: Thực hiện ghép mảng theo chiều ngang (hstack) và dọc (vstack), trích xuất dữ liệu bằng slicing và indexing, cùng các phép toán so sánh và logic nâng cao (all, any, greater).  
Ngẫu nhiên: Sinh dữ liệu ngẫu nhiên theo số nguyên, số thực hoặc phân phối chuẩn Gaussian để phục vụ mô phỏng.

> Thêm khối trích dẫn



# Pandas



In [75]:
import pandas as pd
# Tạo series từ list
a = pd.Series([1., 2., 3.])
print(a)

# Tạo series với index tùy chỉnh
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b['a'])

# Tạo series từ dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
1.0
day1    420
day2    380
day3    390
dtype: int64


In [76]:
# Chuyển từ Numpy sang Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)

# Chuyển từ Pandas ngược lại Numpy
numpy_h = np.array(df_h)

# Tạo DataFrame từ dictionary có tên cột
dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)

# Tạo DataFrame từ mảng ngẫu nhiên 20x4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head()) # In 5 dòng đầu tiên

        so1       so2       so3       so4
0  0.515729  0.357383  0.965817  0.080956
1  0.758279 -0.440642 -0.681174  1.619555
2  0.317867 -0.942234  0.692497 -0.589395
3 -2.008203 -1.335490  1.359553 -0.133816
4 -0.420693 -0.100188 -1.129157 -1.870029


In [77]:


# Khởi tạo DataFrame thứ nhất
df1 = pd.DataFrame({
    'Name': ['John', 'Smith', 'Paul'],
    'Age': [25, 30, 50]
}, index=[0, 1, 2])

# Khởi tạo DataFrame thứ hai
df2 = pd.DataFrame({
    'Name': ['Adam', 'Smith'],
    'Age': [26, 11]
}, index=[3, 4])

# Nối hai DataFrame lại với nhau
df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)

# Xóa những giá trị ở cột Name trùng nhau (Giữ lại giá trị đầu tiên xuất hiện)
print('Drop duplicate values in DataFrame\n', df_concat.drop_duplicates('Name'))

# Sắp xếp DataFrame theo giá trị của cột 'Age' (mặc định là tăng dần)
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))

# Đổi tên cột trong DataFrame
df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicate values in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


# Phần bài tập


PANDAS: Xử lý dữ liệu dạng bảng
Cấu trúc dữ liệu:
Làm việc với Series (1-chiều) và DataFrame (2-chiều), bao gồm việc chuyển đổi qua lại giữa mảng Numpy và bảng Pandas.  
Quản lý tệp: Đọc và xử lý dữ liệu từ các tệp tin CSV, định nghĩa tên cột và xử lý các khoảng trắng thừa.  
Làm sạch & Biến đổi: Nối các bảng (concat), xóa dữ liệu trùng lặp (drop_duplicates), sắp xếp (sort_values) và đổi tên các thuộc tính dữ liệu.  Phân tích: Sử dụng groupby kết hợp các hàm thống kê (trung bình, cực trị, đếm) để tóm tắt thông tin theo nhóm.

In [79]:
import numpy as np

# Bài 1 & 2: Khởi tạo mảng 3x3 ngẫu nhiên [0, 20]
arr = np.random.randint(0, 21, size=(3, 3))
print("Ma trận ngẫu nhiên:\n", arr)

# Bài 1: Kiểm tra tất cả phần tử có khác 0 không
check_all = np.all(arr != 0)
print("Tất cả phần tử khác 0:", check_all)

# Bài 2: Kiểm tra có tồn tại phần tử nào khác 0 không
check_any = np.any(arr != 0)
print("Có ít nhất một phần tử khác 0:", check_any)

Ma trận ngẫu nhiên:
 [[16  9  5]
 [ 5 14 12]
 [15 18 13]]
Tất cả phần tử khác 0: True
Có ít nhất một phần tử khác 0: True


In [80]:
# Bài 3:
# Tạo mảng mẫu
a = np.array([1, 5, 10])
b = np.array([1, 2, 12])

print("Mảng a:", a)
print("Mảng b:", b)

print("a > b  (greater):      ", np.greater(a, b))
print("a >= b (greater_equal):", np.greater_equal(a, b))
print("a < b  (less):         ", np.less(a, b))
print("a <= b (less_equal):   ", np.less_equal(a, b))

# Tương tự cho mảng 2 chiều
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[0, 2], [5, 4]])
print("\nSo sánh ma trận (greater):\n", np.greater(matrix_a, matrix_b))

Mảng a: [ 1  5 10]
Mảng b: [ 1  2 12]
a > b  (greater):       [False  True False]
a >= b (greater_equal): [ True  True False]
a < b  (less):          [False False  True]
a <= b (less_equal):    [ True False  True]

So sánh ma trận (greater):
 [[ True False]
 [False False]]


In [81]:
# Bài 4
# Tạo 10 số 1, 10 số 0 và 10 số 5
arr_1 = np.ones(10)
arr_0 = np.zeros(10)
arr_5 = np.ones(10) * 5

# Nối chúng lại thành một mảng duy nhất bằng hstack [cite: 171]
result_b4 = np.hstack((arr_1, arr_0, arr_5))
print("Mảng bài 4:\n", result_b4)

Mảng bài 4:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [82]:
# Bài 5
# Bắt đầu từ 30, kết thúc trước 71 để lấy được số 70
# Bước nhảy là 2 để chỉ lấy số chẵn
arr_even = np.arange(30, 71, 2)
print("Mảng số chẵn [30, 70]:\n", arr_even)

Mảng số chẵn [30, 70]:
 [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [107]:
# Bài 6
# Viết chương trình tạo ma trận đơn vị 3 x 3 (đường chéo chính bằng 1, các phần tử còn lại 0)
# Sử dụng hàm np.identity hoặc np.eye
identity_matrix = np.identity(3)
print("Ma trận đơn vị 3x3:\n", identity_matrix)

Ma trận đơn vị 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [83]:


# Bài 7: Mảng 10 phần tử [15, 55], in trừ phần tử đầu và cuối
arr7 = np.arange(15, 56) # Tạo dãy số [cite: 301]
# Lấy 10 phần tử đầu tiên để minh họa hoặc dùng linspace
arr7_10 = np.linspace(15, 55, 10)
print("Bài 7 - Các giá trị ở giữa:\n", arr7_10[1:-1]) # Sử dụng Slicing [cite: 319, 441]



Bài 7 - Các giá trị ở giữa:
 [19.44444444 23.88888889 28.33333333 32.77777778 37.22222222 41.66666667
 46.11111111 50.55555556]


In [84]:
# Bài 8: Mảng 20 phần tử [0, 20], đổi dấu số trong khoảng [9, 15]
arr8 = np.arange(21)
arr8[(arr8 >= 9) & (arr8 <= 15)] *= -1 # Đổi dấu giá trị [cite: 442]
print("Bài 8 - Mảng sau khi đổi dấu:\n", arr8)

Bài 8 - Mảng sau khi đổi dấu:
 [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [85]:
# Bài 9: Ma trận 3x4 có giá trị trong khoảng [10, 21]
# Dùng randint để sinh số nguyên ngẫu nhiên [cite: 187]
arr9 = np.random.randint(10, 22, size=(3, 4))
print("Bài 9 - Ma trận 3x4:\n", arr9)

Bài 9 - Ma trận 3x4:
 [[17 16 21 20]
 [20 20 15 10]
 [11 20 19 19]]


In [86]:
# Bài 10: Ma trận 10x10, biên bằng 1, bên trong bằng 0
arr10 = np.ones((10, 10)) # Tạo ma trận toàn số 1 [cite: 68]
arr10[1:-1, 1:-1] = 0     # Gán vùng bên trong bằng 0
print("Bài 10 - Ma trận biên 1:\n", arr10)

Bài 10 - Ma trận biên 1:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#  TENSORFLOW


In [87]:
import tensorflow as tf

# Một Tensor bậc 0 là một giá trị đơn lẻ (scalar)
# Mặc định TensorFlow sẽ coi số nguyên là kiểu int32
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [88]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

# Chỉ định kiểu số nguyên 16-bit (int16)
r1 = tf.constant(9, tf.int16)
print(r1)

# Chỉ định kiểu số thực 32-bit (float32)
r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

# Chỉ định kiểu chuỗi (string)
r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


In [89]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [90]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [91]:
# Rank-3 tensor có thể được coi là một khối dữ liệu (cube)
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [92]:


# Tạo Tensor bậc 1 (Vector) gồm 10 phần tử 0
t_zero = tf.zeros(10)
print(t_zero)
# Kết quả: tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)

# Tạo Tensor bậc 2 (Ma trận) kích thước 3x3 toàn số 0
t_2_zero = tf.zeros([3, 3])
print(t_2_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [94]:
# Tạo tensor 1-chiều có 3 phần tử có giá trị 10
t_1 = tf.fill([3], 10)
print(t_1)

# Tạo tensor 2-chiều kích thước 3x3 có giá trị 9
t_2 = tf.fill([3, 3], 9)
print(t_2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


In [93]:
# Tạo 5 phần tử có giá trị trong khoảng [5.0, 20.0]
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


In [95]:
# Tạo tensor trong khoảng [3.0, 7.0), mỗi giá trị cộng thêm delta = 0.5
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)

# Nếu không khai báo giá trị bắt đầu, mặc định sẽ bắt đầu từ 0.0
range_tensor2 = tf.range(3.0, delta=0.5)
print(range_tensor2)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


In [96]:
# Ngẫu nhiên theo phân phối chuẩn (Normal)
r_normal = tf.random.normal([3, 3])

# Loại bỏ các giá trị nằm ngoài 2 lần độ lệch chuẩn
r_truncated = tf.random.truncated_normal([3, 2])

# Ngẫu nhiên theo phân phối đều (Uniform)
r_uniform = tf.random.uniform([5], minval=10, maxval=20)

# Xáo trộn tensor (Shuffle) theo chiều thứ nhất
shuffled_tensor = tf.random.shuffle(r_uniform)

In [97]:
t_float = tf.constant(3.9, tf.float32)
# Chuyển từ float32 sang int32
t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int)

tf.Tensor(3, shape=(), dtype=int32)


In [98]:
# Tính căn bậc 2
x = tf.constant(2.0, dtype=tf.float32)
print(tf.sqrt(x))

# Cộng và Nhân 2 tensor
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)

c_add = tf.add(a, b)       # Hoặc dùng a + b
c_mul = tf.multiply(a, b)  # Hoặc dùng a * b

tf.Tensor(1.4142135, shape=(), dtype=float32)


In [99]:
# Khai báo biến
toan = tf.Variable(8.5, dtype=tf.float32)
diem = tf.Variable([5, 9])

# Phép gán giá trị mới
diem.assign([8, 10])
diem.assign_add([1, 0]) # Cộng thêm
diem.assign_sub([0, 1]) # Trừ bớt

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([9, 9], dtype=int32)>

In [100]:
import tensorflow as tf

@tf.function
def a_regular_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

# Sử dụng hàm đã được chuyển sang Graph
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[3.0], [4.0]])
b1 = tf.constant([10.0])
print(a_regular_function(x1, y1, b1))

tf.Tensor([[21.]], shape=(1, 1), dtype=float32)


In [101]:
# Tạo một Layer đơn giản
class SimpleModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.a_variable = tf.Variable(5.0, name="train_me")
        self.non_trainable_variable = tf.Variable(5.0, trainable=False, name="do_not_train_me")
    def __call__(self, x):
        return self.a_variable * x + self.non_trainable_variable

# Lưu checkpoint
my_model = SimpleModule(name="simple")
checkpoint = tf.train.Checkpoint(model=my_model)
checkpoint.write("my_checkpoint")

# Phục hồi checkpoint
new_model = SimpleModule()
new_checkpoint = tf.train.Checkpoint(model=new_model)
new_checkpoint.restore("my_checkpoint")

TENSORFLOW: Cơ bản về học sâu
Cấu trúc Tensor:
Làm quen với các bậc Tensor (Rank) từ vô hướng (Scalar), vector đến các khối dữ liệu đa chiều phức tạp.  
Tính toán trên Graph: Chuyển đổi các hàm Python thông thường sang môi trường Graph execution bằng @tf.function để tối ưu hóa tốc độ xử lý song song.  
Xây dựng Mô hình: Tìm hiểu cấu trúc của Modules, Layers và Dense để tạo ra các hàm toán học có khả năng học hỏi từ dữ liệu.  
Quản lý trạng thái: Sử dụng tf.Variable cho các giá trị có thể cập nhật và lưu trữ/phục hồi tiến trình huấn luyện thông qua Checkpoint.

# Bài tập

In [102]:
# Bài 1: Tạo tensor 2x3 toàn số 0
b1 = tf.zeros([2, 3])
print("Bài 1:\n", b1)

Bài 1:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [103]:
# Cho X
X = [[1, 2, 3], [4, 5, 6]]

# Bài 2: Tạo tensor có cùng shape và dtype với X nhưng toàn số 0
b2 = tf.zeros_like(X)
print("Bài 2:\n", b2)

Bài 2:
 tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [104]:
# Bài 3: Tạo ma trận 3x2 toàn số 5
b3 = tf.fill([3, 2], 5)
print("Bài 3:\n", b3)

Bài 3:
 tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


In [105]:
# Bài 4: Tạo 50 phần tử từ 6.0 đến 10.0
# Lưu ý: Các giá trị sẽ là số thực để chia đều 50 khoảng
b4 = tf.linspace(6.0, 10.0, 50)
print("Bài 4:\n", b4)

Bài 4:
 tf.Tensor(
[ 6.         6.0816326  6.163265   6.244898   6.3265305  6.408163
  6.4897957  6.5714283  6.6530614  6.734694   6.8163266  6.897959
  6.979592   7.0612245  7.142857   7.2244897  7.3061223  7.387755
  7.469388   7.5510206  7.632653   7.714286   7.7959185  7.877551
  7.9591837  8.040816   8.122449   8.204082   8.285714   8.367347
  8.448979   8.530612   8.612245   8.693877   8.77551    8.857142
  8.938776   9.020409   9.102041   9.183674   9.265306   9.346939
  9.428572   9.510204   9.591837   9.67347    9.755102   9.836735
  9.918367  10.       ], shape=(50,), dtype=float32)


In [106]:
# Bài 5: Bắt đầu từ 10, kết thúc tại 101 (để bao gồm số 100), bước nhảy là 2
b5 = tf.range(10, 101, delta=2)
print("Bài 5:\n", b5)

Bài 5:
 tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)
